export const AJAX_STATUS_ERROR = 'AJAX_STATUS_ERROR'
export const AJAX_NETWORK_ERROR = 'AJAX_NETWORK_ERROR'
export const AjAX_RESPONSE_TIME = 'AjAX_RESPONSE_TIME'

export const LOAD_SOURCE_ERROR = 'LOAD_SOURCE_ERROR'
export const SCRIPT_EXECUTE_ERROR = 'SCRIPT_EXECUTE_ERROR'
export const AJAX_RESPONSE_TIME = 'AJAX_RESPONSE_TIME' 


